(define (problem blocksworld-6)
  (:domain blocksworld)
  (:objects b1 b2 b3 b4 b5 b6)
  (:init
    (ontable b4)
    (on b3 b4)
    (on b1 b3)
    (clear b1)
    (ontable b2)
    (on b5 b2)
    (on b6 b5)
    (clear b6)
    (handempty)
  )
  (:goal
    (and
    (ontable b4)
    (on b3 b4)
    (clear b3)
    (ontable b5)
    (on b6 b5)
    (clear b6)
    (ontable b1)
    (on b2 b1)
    (clear b2)
    )
  )
)
