(define (problem blocksworld-8)
  (:domain blocksworld)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (ontable b4)
    (on b3 b4)
    (clear b3)
    (ontable b5)
    (on b6 b5)
    (clear b6)
    (ontable b7)
    (on b1 b7)
    (clear b1)
    (ontable b8)
    (on b2 b8)
    (clear b2)
    (handempty)
  )
  (:goal
    (and
    (ontable b5)
    (on b6 b5)
    (on b2 b6)
    (clear b2)
    (ontable b8)
    (on b1 b8)
    (on b4 b1)
    (clear b4)
    (ontable b7)
    (on b3 b7)
    (clear b3)
    )
  )
)
