(define (problem blocksworld-10)
  (:domain blocksworld)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (ontable b8)
    (on b7 b8)
    (clear b7)
    (ontable b4)
    (on b10 b4)
    (clear b10)
    (ontable b3)
    (on b5 b3)
    (clear b5)
    (ontable b9)
    (on b1 b9)
    (clear b1)
    (ontable b6)
    (on b2 b6)
    (clear b2)
    (handempty)
  )
  (:goal
    (and
    (ontable b7)
    (on b10 b7)
    (on b1 b10)
    (on b4 b1)
    (clear b4)
    (ontable b5)
    (on b8 b5)
    (on b6 b8)
    (clear b6)
    (ontable b2)
    (on b9 b2)
    (on b3 b9)
    (clear b3)
    )
  )
)
